import type { AppProps } from 'next/app';
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import '@/styles/globals.css';

// amplify_outputs.json is generated by `npx ampx sandbox` (dev)
// or by Amplify Hosting's build (production). See README.md.
let configured = false;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const outputs = require('../amplify_outputs.json');
  const hasAuthConfiguration = Boolean(
    outputs.auth?.user_pool_id && outputs.auth?.user_pool_client_id,
  );

  if (hasAuthConfiguration) {
    Amplify.configure(outputs, { ssr: true });
    configured = true;
  }
} catch {
  // Not generated yet — run `npx ampx sandbox` first.
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      {!configured ? (
        <div className="bg-amber-100 px-4 py-2 text-center text-sm text-amber-900">
          AWS is not configured yet. Run <code>npx ampx sandbox</code> to generate{' '}
          <code>amplify_outputs.json</code> (see README).
        </div>
      ) : null}
      <Component {...pageProps} />
    </>
  );
}
